### ISSUE TITLE
Badges for 3 days in a row and 7 days in a row missing

### ISSUE THREAD

**Issue by bobismijnnaam** [ellenbrook/morningpages#34]
As the title states, it seems that badges for the second and third badge are missing/not functioning. I've looked at the morningpages source and it seems that (as the actual path to the badges is not stored in this repo) either the png files are either incorrectly named (in the code it is referred to as a hattrick, but the png is name 3-days-in-a-row.png or something) or not stored correctly in the achievements database. Could anyone have a short look at this or provide me a brief overview on how to set this up locally (ubuntu 15.04 or windows 8 please (; ) so I can give it a go myself?

Kind regards, a concerned morningpages user

**Comment by ellenbrook** [comment]
Hi @bobismijnnaam,

Just wanted to give you a heads up that I've fixed the issue and I'm working on a way to update everyone's account to reflect the previous badges.  We'll give a post on the forum as soon as that's done. But from now on any new badges will be assigned properly.
