### ISSUE TITLE
30 day challenge doesn't show correct stats

### ISSUE THREAD

**Issue by arunrreddy** [ellenbrook/morningpages#36]
My current writing streak on /me page is 14 days but the 30-day challenge shows that  my current writing streak is 12 days.

**Comment by danielvalentin** [comment]
You didn't start the challenge 12 days ago, but already had a 2 day streak going?

**Comment by arunrreddy** [comment]
Oh yes, you are right. Thanks for jogging my memory.

**Comment by danielvalentin** [comment]
Haha, no problem! Thanks for reporting it never the less :)
